"""
Django settings for opal project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import secrets
from pathlib import Path
import os

#Path variables for application
BASE_DIR = str(Path(__file__).resolve(strict=True).parent.parent)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'
IMPORTED_CATALOGS_DIR = 'catalogs/'

# Other Variables
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2048
ROOT_URLCONF = 'opal.urls'
WSGI_APPLICATION = 'opal.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'EST'
USE_I18N = True
USE_L10N = True
USE_TZ = True


#All of the following values MUST be defined as environment variables in your system
env_var = [
    "env", #development or production
    "opal_secret_key", #secret key used to create sessions
    "debug", #True of False
    "allowed_hosts", #Must be a comma seperated list of acceptable host names to use when accessing the application. Use '*' for all
    "database", #sqlite or postgres
    "db_password", #can be blank if using sqlite
    "db_name", #name of db in postgres, can be blank if using sqlite
    "db_user", #can be blank if using sqlite
    "db_host", #can be blank if using sqlite
    "db_port", #can be blank if using sqlite
    "adfs_enabled", #True or False
    "adfs_server", #can be blank if adfs_enabled is False
    "adfs_client_id", #can be blank if adfs_enabled is False
    "adfs_client_id", #can be blank if adfs_enabled is False
    "adfs_relying_party_id", #can be blank if adfs_enabled is False
    "adfs_audience" #can be blank if adfs_enabled is False
]

env = {"env":"development","debug":"True","database":"mysql","adfs_enabled":"False"}

for k in env_var:
    if k == "allowed_hosts":
        # allowed_hosts must be a list
        env[k] = os.getenv(k,'*').split(',')
    elif k == "opal_secret_key":
        env[k] = os.getenv(k,secrets.token_urlsafe())
    elif k in env.keys():
        env[k] = os.getenv(k,env[k])
    else:
        env[k] = os.getenv(k,'')

if env["env"] == "development":
    print("Running in Development mode!")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env["opal_secret_key"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env["debug"]
ALLOWED_HOSTS = env["allowed_hosts"]


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'dal_queryset_sequence',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'django_extensions',
    'fixture_magic',
    'rest_framework',
    'rest_framework_tricks',
    'ssp.apps.ssp',
    'coverage',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.contrib.staticfiles',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ssp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if env["database"] == "postgres":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env['db_name'],
            'USER': env['db_user'],
            'PASSWORD': env["db_password"],
            'HOST': env["db_host"],
            'PORT': env["db_port"],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR + '/db.sqlite3',
        }
    }

REST_FRAMEWORK = {
    # TODO enable ADFS for REST Framework https://django-auth-adfs.readthedocs.io/en/latest/rest_framework.html
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework_json_api.pagination.JsonApiPageNumberPagination',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework_json_api.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
        # If you're performance testing, you will want to use the browseable API
        # without forms, as the forms can generate their own queries.
        # If performance testing, enable:
        # 'example.utils.BrowsableAPIRendererWithoutForms',
        # Otherwise, to play around with the browseable API, enable:
        'rest_framework.renderers.BrowsableAPIRenderer'
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework_json_api.metadata.JSONAPIMetadata',
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_json_api.filters.QueryParameterValidationFilter',
        'rest_framework_json_api.filters.OrderingFilter',
        'rest_framework_json_api.django_filters.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),
    'SEARCH_PARAM': 'filter[search]',
    'TEST_REQUEST_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'vnd.api+json'
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    )

if env["adfs_enabled"] == "True":
    INSTALLED_APPS.append('django_auth_adfs')

    # With this you can force a user to login without using
    # the LoginRequiredMixin on every view class
    #
    # You can specify URLs for which login is not enforced by
    # specifying them in the LOGIN_EXEMPT_URLS setting.
    MIDDLEWARE.append('django_auth_adfs.middleware.LoginRequiredMiddleware',)

    AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
    )

    # checkout the documentation of django_auth_adfs for more settings
    AUTH_ADFS = {
        "SERVER": env["adfs_server"],
        "CLIENT_ID": env["adfs_client_id"],
        "RELYING_PARTY_ID": env["adfs_relying_party_id"],
        # Make sure to read the documentation about the AUDIENCE setting
        # when you configured the identifier as a URL!
        "AUDIENCE": env["adfs_audience"],
        # "CA_BUNDLE": "/path/to/ca-bundle.pem",
        "CLAIM_MAPPING": {"first_name": "given_name",
                        "last_name": "family_name",
                        "email": "email"},
        "USERNAME_CLAIM": "upn",
        "GROUP_CLAIM": "group"
        }

    # Configure django to redirect users to the right URL for login
    LOGIN_URL = "django_auth_adfs:login"
    LOGIN_REDIRECT_URL = "/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR,'debug.log')
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file','console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
