# Generated by Django 4.1.7 on 2023-02-23 19:58

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_controls_sort_id'),
        ('ctrl_profile', '0001_squashed_0004_remove_imports_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imports',
            name='include_all',
            field=models.BooleanField(default=True, help_text='Choose this option to include all controls from the imported catalog or profiles', verbose_name='Include all controls'),
        ),
        migrations.AlterField(
            model_name='modify',
            name='set_parameters',
            field=common.models.CustomManyToManyField(help_text='Select any parameters you wish to modify', to='catalog.params', verbose_name='Modified Parameters'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='modify',
            field=models.ForeignKey(help_text='Define parameters and controls that are modified by this profiles.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ctrl_profile.modify', verbose_name='Modifications'),
        ),
    ]
