# Generated by Django 4.2 on 2023-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_catalogs_controls_alter_catalogs_groups_and_more'),
        ('ctrl_profile', '0001_squashed_0005_alter_imports_include_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imports',
            name='exclude_controls',
            field=models.ManyToManyField(help_text='Select the controls to be excluded. Any controls not explicitly selected will be excluded', related_name='exclude_controls', to='catalog.controls', verbose_name='Excluded Controls'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='include_controls',
            field=models.ManyToManyField(help_text='Select the controls to be included. Any controls not explicitly selected will be excluded', related_name='include_controls', to='catalog.controls', verbose_name='Included Controls'),
        ),
        migrations.AlterField(
            model_name='modify',
            name='alters',
            field=models.ManyToManyField(help_text='Select any controls you wish to modify', to='catalog.controls', verbose_name='Modified Controls'),
        ),
        migrations.AlterField(
            model_name='modify',
            name='set_parameters',
            field=models.ManyToManyField(help_text='Select any parameters you wish to modify', to='catalog.params', verbose_name='Modified Parameters'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='imports',
            field=models.ManyToManyField(help_text='The import designates a catalog, profiles, or other resource to be included (referenced and potentially modified) by this profiles. The import also identifies which controls to select using the include-all, include-controls, and exclude-controls directives.', to='ctrl_profile.imports', verbose_name='Imports'),
        ),
    ]
