apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: opal-db
  name: opal-db-postgres-volume-claim
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
