apiVersion: v1
kind: Service
metadata:
  name: opal-db
  namespace: {{ .Values.namespace | quote }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    component: opal-db
  sessionAffinity: None
  type: ClusterIP