apiVersion: v1
data:
  POSTGRES_OPAL_PASSWORD: {{ .Values.secret.postgres_opal_password | b64enc | quote }} 
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password | b64enc | quote }} 
kind: Secret
metadata:
  name: opal-passwords
  namespace: {{ .Values.namespace | quote }}
type: Opaque
