apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opal
  template:
    metadata:
      labels:
        component: opal
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: {{ .Values.env }}
        - name: DEBUG
          value: "False"
        - name: LOG_LEVEL
          value: INFO
        - name: HOST_NAME
          value: {{ .Values.hostname }}
        - name: SECRET_KEY
          value: 20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE
        - name: ALLOWED_HOSTS
          value: {{ .Values.hostname }}
        - name: SSL_ACTIVE
          value: "True"
        - name: ENABLE_SAML
          value: "True"
        - name: HTTP_PROXY
          value: {{ .Values.proxy.http_proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy.https_proxy }}
        - name: DATABASE
          value: postgres
        - name: DB_HOST
          value: opal-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: opal
        - name: DB_NAME
          value: opal
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_OPAL_PASSWORD
              name: opal-passwords
        image: {{ .Values.repo.webapp }}/opal:latest
        imagePullPolicy: Always
        name: opal
        ports:
        - containerPort: 8000
          name: 8000tcp
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 1001
      restartPolicy: Always