apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opal-ingress
  namespace: {{ .Values.namespace | quote }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: opal
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.tls_secret }}
