# Generated by Django 4.1.3 on 2022-12-30 21:51

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_addresses_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='rel',
            field=common.models.ShortTextField(blank=True, choices=[('related', 'related'), ('moved-to', 'moved-to'), ('canonical', 'canonical'), ('incorporated-into', 'incorporated-into'), ('required', 'required'), ('reference', 'reference'), ('alternate', 'alternate')], help_text="Describes the type of relationship provided by the link. This can be an indicator of the link's purpose.", verbose_name='Relation'),
        ),
    ]
