# Generated by Django 4.1.7 on 2023-02-23 20:33

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_squashed_0005_alter_links_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='oscal_version',
            field=common.models.ShortTextField(default='1.0.0', help_text='The OSCAL model version the document was authored against.', verbose_name='OSCAL Version'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='version',
            field=common.models.ShortTextField(default='1.0', help_text='A string used to distinguish the current version of the document from other previous (and future) versions.', verbose_name='Document Version'),
        ),
        migrations.AlterField(
            model_name='props',
            name='ns',
            field=common.models.ShortTextField(default='https://csrc.nist.gov/ns/oscal', help_text="A namespace qualifying the property's name. This allows different organizations to associate distinct semantics with the same name.", verbose_name='Property Namespace'),
        ),
    ]
