# Generated by Django 4.1.7 on 2023-02-23 20:35

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_metadata_oscal_version_alter_metadata_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='oscal_version',
            field=common.models.ShortTextField(default='v1.0.3', help_text='The OSCAL model version the document was authored against.', verbose_name='OSCAL Version'),
        ),
    ]
