# Generated by Django 4.2.5 on 2023-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_back_matter_resources_alter_citations_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='responsible_parties',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Role Links'),
        ),
    ]
