# Generated by Django 4.2.5 on 2023-10-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_citations_links_alter_metadata_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='href',
            field=models.URLField(help_text='A resolvable URL reference to a resource.', verbose_name='URL'),
        ),
    ]
