# Generated by Django 4.2.5 on 2023-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_links_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='document_ids',
            field=models.ManyToManyField(blank=True, to='common.document_ids', verbose_name='Other Document IDs'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='locations',
            field=models.ManyToManyField(blank=True, to='common.locations', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='parties',
            field=models.ManyToManyField(blank=True, help_text='A responsible entity which is either a person or an organization.', to='common.parties', verbose_name='Parties (organizations or persons)'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, help_text=' A reference to a set of organizations or persons that have responsibility for performing a referenced role in the context of the containing object.', to='common.responsible_parties', verbose_name='Responsible Parties'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='revisions',
            field=models.ManyToManyField(blank=True, to='common.revisions', verbose_name='Previous Revisions'),
        ),
    ]
