# Generated by Django 4.2.5 on 2024-01-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_back_matter_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisions',
            name='published',
            field=models.DateTimeField(help_text='The date and time the document was published. The date-time value must be formatted according to RFC 3339 with full time and time zone included.', null=True, verbose_name='Publication Timestamp'),
        ),
    ]
