apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opal
  template:
    metadata:
      labels:
        component: opal
    spec:
      containers:
        - name: opal
          # Change this value to reflect your repository and image name
          image:  opal2
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: 20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE
            # this configuration assumes you are going to deploy a second container running postgres to serve as the
            # database for opal. If you prefer to use sqlite or some other database modify the settings below
            # as needed.  Consult the readme.md file in the project root for details about environment variables.
            - name: DATABASE
              value: postgres
            - name: DB_HOST
              value: opal-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: opal
            - name: DB_NAME
              value: opal
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opal-passwords
                  key: POSTGRES_OPAL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: opal
spec:
  type: ClusterIP
  selector:
    component: opal
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opal-ingress
# uncomment these 2 lines to enable https
#  annotations:
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  # Make sure to modify the host value to reflect the url you wish to access opal from
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: opal
            port:
              number: 80
        pathType: ImplementationSpecific
# uncomment these 4 lines to enable https
#  tls:
# Make sure to modify the host value to reflect the url you wish to access opal from
#  - hosts:
#    - localhost
#    secretName: opal-ingress-tls
---
# The following sections deploy a postgres server container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opal-db
  template:
    metadata:
      labels:
        component: opal-db
    spec:
      containers:
        - name: opal-db
          # Change this value to reflect your repository and image name
          image: localhost:5000/opal-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opal-passwords
                  key: POSTGRES_PASSWORD
            - name: DB_USER
              value: opal
            - name: POSTGRES_OPAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opal-passwords
                  key: POSTGRES_OPAL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: opal-db
spec:
  type: ClusterIP
  selector:
    component: opal-db
  ports:
    - port: 5432
      targetPort: 5432