apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: opal-db
  name: {{ .Values.volume_name }}
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: {{ .Values.volume_name }}

