apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opal
      app: opal
  template:
    metadata:
      labels:
        component: opal
        app: opal
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
      - image: {{ .Values.repo.webapp }}/opal:{{ .Values.version }}
        imagePullPolicy: Always
        name: opal
        ports:
        - containerPort: 8000
          name: 8000tcp
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: {{ .Values.env }}
        - name: DEBUG
          value: "False"
        - name: LOG_LEVEL
          value: INFO
        - name: HOST_NAME
          value: {{ .Values.hostname }}
#        - name: SECRET_KEY
#          value: 20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE
        - name: ALLOWED_HOSTS
          value: {{ .Values.hostname }}
        - name: SSL_ACTIVE
          value: "True"
        - name: ENABLE_SAML
          value: '{{ .Values.saml.ENABLE_SAML }}'
        - name: SAML_PROVIDERS
          value: '{{ .Values.saml.SAML_PROVIDERS }}'
        - name: SAML_HTTPS
          value: '{{ .Values.saml.SAML_HTTPS }}'
        - name: SAML_HTTP_HOST
          value: '{{ .Values.saml.SAML_HTTP_HOST }}'
        - name: SAML_SERVER_PORT
          value: '{{ .Values.saml.SAML_SERVER_PORT }}'
        - name: HTTP_PROXY 
          value: {{ .Values.proxy.http_proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy.https_proxy }}
        - name: DATABASE
          value: postgres
        - name: DB_HOST
          value: opal-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: opal
        - name: DB_NAME
          value: opal
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_OPAL_PASSWORD
              name: opal-passwords
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: "RuntimeDefault"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-secret