apiVersion: v1
metadata:
  name: opal-passwords
  namespace: {{ .Values.namespace }}
kind: Secret
type: Opaque
data:
  POSTGRES_OPAL_PASSWORD: {{ .Values.secret.postgres_opal_password | b64enc | quote }} 
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password | b64enc | quote }} 
