# Generated by Django 4.0.6 on 2022-07-27 20:30

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_squashed_0003_alter_control_implementations_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='by_components',
            name='implemented_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.implemented_requirements'),
        ),
        migrations.AlterField(
            model_name='components',
            name='type',
            field=common.models.ShortTextField(choices=[('this-system', 'This System: The system as a whole.'), ('system', 'Another System: An external system, which may be a leveraged system or the other side of an interconnection.'), ('interconnection', 'System Interconnection: A connection to something outside this system.'), ('software', 'Software: Any software, operating system, or firmware.'), ('hardware', 'Hardware: A physical device.'), ('service', 'Service: A service that may provide APIs.'), ('policy', 'Policy: An enforceable policy.'), ('physical', 'Physical: A tangible asset used to provide physical protections or countermeasures.'), ('process-procedure', 'Process or Procedure: A list of steps or actions to take to achieve some end result.'), ('plan', 'Plan: An applicable plan.'), ('guidance', 'Guidance: Any guideline or recommendation.'), ('standard', 'Standard: Any organizational or industry standard.'), ('validation', 'Validation: An external assessment performed on some other component, that has been validated by a third-party.'), ('network', 'Network: A physical or virtual network.')], help_text='A category describing the purpose of the component.', verbose_name='Component Type'),
        ),
        migrations.AlterField(
            model_name='statements',
            name='implemented_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.implemented_requirements'),
        ),
    ]
