# Generated by Django 4.0.6 on 2022-07-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='control_implementations',
        ),
        migrations.RemoveField(
            model_name='control_implementations',
            name='implemented_requirements',
        ),
        migrations.RemoveField(
            model_name='implemented_requirements',
            name='by_components',
        ),
        migrations.RemoveField(
            model_name='implemented_requirements',
            name='statements',
        ),
        migrations.AddField(
            model_name='by_components',
            name='implemented_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.implemented_requirements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_implementations',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.components'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='implemented_requirements',
            name='control_implementation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.control_implementations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='by_component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.by_components'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statements',
            name='implemented_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.implemented_requirements'),
            preserve_default=False,
        ),
    ]
