# Generated by Django 4.1 on 2022-08-30 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_by_components_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='by_components',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes how a control or a control statement is implemented within the referenced system component.', verbose_name='Control Implementation Description'),
        ),
        migrations.AlterField(
            model_name='by_components',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='components',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='A description of the component, including information about its function.', verbose_name='Component Description'),
        ),
        migrations.AlterField(
            model_name='components',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='control_implementations',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Describes how the system satisfies a set of controls.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='control_implementations',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='export',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes the aspects of the control or control statement implementation that can be available to another system leveraging this system.', verbose_name='Control Implementation Export Description'),
        ),
        migrations.AlterField(
            model_name='export',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='implemented_requirements',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='inherited',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes the aspects of a control or control statement implementation that a leveraging system is inheriting from a leveraged system.', verbose_name='Control Implementation Responsibility Description'),
        ),
        migrations.AlterField(
            model_name='inherited',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='provided_control_implementation',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes the aspects of the control or control statement implementation that can be provided to another system leveraging this system.', verbose_name='Provided Control Implementation Description'),
        ),
        migrations.AlterField(
            model_name='provided_control_implementation',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='responsibilities',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes the aspects of the control or control statement implementation that a leveraging system must implement to satisfy the control provided by a leveraged system.', verbose_name='Control Implementation Responsibility Description'),
        ),
        migrations.AlterField(
            model_name='responsibilities',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='responsible_roles',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='satisfied',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='An implementation statement that describes the aspects of a control or control statement implementation that a leveraging system is inheriting from a leveraged system.', verbose_name='Control Implementation Responsibility Description'),
        ),
        migrations.AlterField(
            model_name='satisfied',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='statements',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
    ]
