# Generated by Django 4.1.3 on 2022-12-28 19:49

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_remove_by_components_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implemented_requirements',
            name='control_implementation',
        ),
        migrations.AddField(
            model_name='control_implementations',
            name='implemented_requirements',
            field=common.models.CustomManyToManyField(help_text='Set of controls implemented by this component', to='component.implemented_requirements', verbose_name='Implimented Requirements'),
        ),
    ]
