# Generated by Django 4.1.3 on 2022-12-28 19:50

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_remove_implemented_requirements_control_implementation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_implementations',
            name='implemented_requirements',
            field=common.models.CustomManyToManyField(help_text='Set of controls implemented by this component', to='component.implemented_requirements', verbose_name='Implemented Requirements'),
        ),
    ]
