# Generated by Django 4.1.5 on 2023-03-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_squashed_0007_alter_components_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemented_requirements',
            name='control_implementation',
            field=models.ForeignKey(help_text='The Control Implementation set this implementation is a part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci', to='component.control_implementations', verbose_name='control implementation'),
        ),
    ]
