# Generated by Django 4.1.5 on 2023-03-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_implemented_requirements_control_implementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='implemented_requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='component.implemented_requirements'),
        ),
    ]
