# Generated by Django 4.1.5 on 2023-03-27 15:31

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_parameters_implemented_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implemented_requirements',
            name='control_implementation',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='implemented_requirement',
        ),
        migrations.AddField(
            model_name='parameters',
            name='control_implementations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='component.control_implementations'),
        ),
        migrations.AlterField(
            model_name='control_implementations',
            name='set_parameters',
            field=common.models.CustomManyToManyField(help_text='Use of set-parameter in this context, sets the parameter for all related controls referenced in an implemented-requirement. If the same parameter is also set in a specific implemented-requirement, then the new value will override this value.', related_name='set_parameters', to='component.parameters', verbose_name='Common Parameters'),
        ),
    ]
