# Generated by Django 4.1.5 on 2023-03-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0010_remove_implemented_requirements_control_implementation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='by_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='component.by_components'),
        ),
    ]
