# Generated by Django 4.2 on 2023-06-14 18:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_squashed_0011_alter_parameters_by_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_implementations',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Describes how the system satisfies a set of controls.', null=True, verbose_name='Description'),
        ),
    ]
