# Generated by Django 4.2.5 on 2024-01-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0015_alter_by_components_inherited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'ordering': ('type', 'title'), 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
    ]
