# Generated by Django 4.1 on 2022-08-27 02:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.available_catalog_list', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='available_catalog_list',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.catalogs', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='catalogs',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.constraints', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='constraints',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.controls', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='controls',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.groups', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.guidelines', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='guidelines',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.params', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='params',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.parts', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_ancestors_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_ancestors_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_children_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_children_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Children pks'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_depth',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_descendants_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_descendants_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_level',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='catalog.tests', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_siblings_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tn_siblings_pks',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks'),
        ),
    ]
