# Generated by Django 4.0.6 on 2022-07-19 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_available_catalog_list_catalog_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_catalog_list',
            name='slug',
        ),
    ]
