# Generated by Django 4.1.3 on 2022-12-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_controls_options_controls_sort_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controls',
            options={'ordering': ['sort_id'], 'verbose_name': 'Control', 'verbose_name_plural': 'Controls'},
        ),
    ]
