# Generated by Django 4.2 on 2023-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_catalogs_catalog_uuid_alter_catalogs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogs',
            name='catalog_uuid',
            field=models.UUIDField(null=True, verbose_name='Catalog Universally Unique Identifier'),
        ),
    ]
