# Generated by Django 4.2.5 on 2023-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_citations_links_alter_metadata_links_and_more'),
        ('catalog', '0010_alter_catalogs_controls_alter_catalogs_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_catalog_list',
            name='catalog_uuid',
            field=models.UUIDField(help_text='The UUID for this catalog. All catalogs MUST have a unique UUID which should be the same across multiple systems.', unique=True),
        ),
        migrations.AlterField(
            model_name='controls',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='params',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
    ]
