version: "3.9"

services:
  db:
    build: ../postgres
    ports:
      - "65432:5432"
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=opal
      - POSTGRES_USER=opal
      - POSTGRES_PASSWORD=use_a_secure_password_here
  broker:
    image: rabbitmq
    ports:
      - "5672:5672"
  web:
    build: ../../
    user: opal
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OPAL_SECRET_KEY='20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE'
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - DATABASE=postgres
      - DB_NAME=opal
      - DB_USER=opal
      - DB_HOST=db
      - DB_PORT=65432
      - DB_PASSWORD=use_a_secure_password_here
      - ALLOWED_HOSTS=127.0.0.1,localhost,web,192.168.42.105
      - ASYNC=True
      - BROKER=pyamqp://broker:5672//
      - HOST_NAME=localhost:8000
      - ENABLE_SAML=True
    depends_on:
      - db