version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=opal
      - POSTGRES_USER=opal
      - POSTGRES_PASSWORD=use_a_secure_password_here
  web:
    build: ../../
    user: root
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver_plus 127.0.0.1:8888"
    ports:
      - "8888:8888"
#    volumes:
#      - ../../:/usr/src/app
    environment:
      - OPAL_SECRET_KEY='20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE'
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - DATABASE=postgres
      - DB_NAME=opal
      - DB_USER=opal
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=use_a_secure_password_here
      - ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on:
      - db