version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=opal
      - POSTGRES_USER=opal
      - POSTGRES_PASSWORD=use_a_secure_password_here
  broker:
    image: rabbitmq
    ports:
      - "15672:15672"
  web:
    build: ../../
    user: root
    restart: always
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../../catalog:/usr/src/app/catalog
      - ../../common:/usr/src/app/common
      - ../../component:/usr/src/app/component
      - ../../profile:/usr/src/app/profile
      - ../../ssp:/usr/src/app/ssp
    environment:
      - OPAL_SECRET_KEY='20mUVZU8a-aVUoEzvWX-b5QWIvpGFQULfFhhsCdwRpE'
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - DATABASE=postgres
      - DB_NAME=opal
      - DB_USER=opal
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=use_a_secure_password_here
      - ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on:
      - db