# Generated by Django 3.0.7 on 2020-08-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20200825_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_security_plan',
            name='control_baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.control_group'),
        ),
    ]
