# Generated by Django 3.0.7 on 2020-08-25 18:39

from django.db import migrations
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0003_auto_20200825_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='control_group',
            new_name='control_baseline',
        ),
        migrations.AlterField(
            model_name='control_baseline',
            name='controls',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.nist_control'),
        ),
    ]
