# Generated by Django 3.0.7 on 2020-08-25 19:06

from django.db import migrations, models
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0005_auto_20200825_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='leveraged_system_name',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='link_to_SSP',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='links',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='ssp',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='title',
        ),
        migrations.RemoveField(
            model_name='leveraged_authorization',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='system_characteristic',
            name='leveraged_authorizations',
        ),
        migrations.AddField(
            model_name='leveraged_authorization',
            name='foo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='leveraged_authorization',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.system_security_plan'),
        ),
    ]
