# Generated by Django 3.0.7 on 2020-08-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0006_auto_20200825_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leveraged_authorization',
        ),
    ]
