# Generated by Django 3.0.7 on 2020-09-29 21:41

from django.db import migrations
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0011_auto_20200826_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_control',
            name='control_parameters',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.control_parameter'),
        ),
        migrations.AddField(
            model_name='system_control',
            name='control_responsible_roles',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.user_role'),
        ),
        migrations.AddField(
            model_name='system_control',
            name='control_statements',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.control_statement'),
        ),
    ]
