# Generated by Django 3.0.7 on 2020-09-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0012_auto_20200929_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_control',
            name='control_implementation',
        ),
        migrations.DeleteModel(
            name='control_implementation',
        ),
    ]
