# Generated by Django 3.0.7 on 2020-09-30 19:32

from django.db import migrations, models
import django.db.models.deletion
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0013_auto_20200929_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_control',
            name='control_responsible_roles',
        ),
        migrations.RemoveField(
            model_name='system_control',
            name='information_system',
        ),
        migrations.RemoveField(
            model_name='system_control',
            name='inheritable',
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='authorization_boundary_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_authorization_boundary_diagram', to='ssp.attachment'),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='data_flow_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_data_flow_diagram', to='ssp.attachment'),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='date_authorized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='network_architecture_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_network_architecture_diagram', to='ssp.attachment'),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='security_objective_availability',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='security_objective_confidentiality',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='security_objective_integrity',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='security_sensitivity_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='system_information',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.system_information_type'),
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='system_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.status'),
        ),
    ]
