# Generated by Django 3.0.7 on 2020-09-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0014_auto_20200930_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_security_plan',
            name='system_characteristics',
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='authorization_boundary_diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_authorization_boundary_diagram', to='ssp.attachment'),
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='data_flow_diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_data_flow_diagram', to='ssp.attachment'),
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='network_architecture_diagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_network_architecture_diagram', to='ssp.attachment'),
        ),
        migrations.DeleteModel(
            name='system_characteristic',
        ),
    ]
