# Generated by Django 3.0.7 on 2020-08-18 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_squashed_0032_auto_20200818_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_property',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='email',
            name='supports_rich_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
