# Generated by Django 3.1.5 on 2021-01-29 18:42

from django.db import migrations, models
import django.db.models.deletion
import ssp.models.base_classes_and_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_squashed_0004_system_control_control_primary_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_baseline',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_baseline_set', to='ssp.link'),
        ),
        migrations.CreateModel(
            name='import_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/catalogs/')),
                ('added_controls', models.IntegerField(blank=True, null=True)),
                ('updated_controls', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('control_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='import_catalog_set', to='ssp.control_baseline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='continuous_monitoring_action_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, help_text='A title for display and navigation', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='A common name, short name, or acronym', max_length=255)),
                ('desc', ssp.models.base_classes_and_fields.customTextField(help_text='A short textual description', verbose_name='description')),
                ('remarks', ssp.models.base_classes_and_fields.customTextField(help_text='general notes or comments')),
                ('automated', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('as needed', 'As Needed')], default='as needed', max_length=10)),
                ('control_statements', ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.control_statement')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
