# Generated by Django 3.1 on 2020-08-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_characteristic',
            name='date_authorized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='system_characteristic',
            name='security_sensitivity_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=30),
        ),
        migrations.AlterField(
            model_name='system_characteristic',
            name='system_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.status'),
        ),
    ]
