# Generated by Django 3.1.4 on 2020-12-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_squashed_0002_auto_20201222_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_component',
            name='component_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_component_set', to='ssp.status'),
        ),
        migrations.AlterField(
            model_name='system_control',
            name='nist_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_control_set', to='ssp.nist_control'),
        ),
        migrations.AlterField(
            model_name='system_inventory_item',
            name='inventory_item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_inventory_item_set', to='ssp.inventory_item_type'),
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='control_baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssp_control_baseline_set', to='ssp.control_baseline'),
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='system_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssp_system_status_set', to='ssp.status'),
        ),
    ]
