# Generated by Django 3.0.7 on 2020-08-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_squashed_0006_system_control_information_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_control',
            name='information_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.system_security_plan'),
        ),
    ]
