# Generated by Django 4.1 on 2022-08-30 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_authorization_boundaries_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization_boundaries',
            name='description',
            field=ckeditor.fields.RichTextField(help_text="A summary of the system's authorization boundary.", verbose_name='Authorization Boundary Description'),
        ),
        migrations.AlterField(
            model_name='authorization_boundaries',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='data_flows',
            name='description',
            field=ckeditor.fields.RichTextField(help_text="A summary of the system's Data Flow.", verbose_name='Data Flow Description'),
        ),
        migrations.AlterField(
            model_name='data_flows',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='diagrams',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A summary of the diagram. This description is intended to be used as alternate text to support compliance with requirements from Section 508 of the United States Workforce Rehabilitation Act of 1973.', verbose_name='Diagram Description'),
        ),
        migrations.AlterField(
            model_name='diagrams',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='import_profiles',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='information_type_impact_level',
            name='adjustment_justification',
            field=ckeditor.fields.RichTextField(help_text='If the selected security level is different from the base security level, this contains the justification for the change.', null=True, verbose_name='Adjustment Justification'),
        ),
        migrations.AlterField(
            model_name='information_type_impact_level',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='A summary of the inventory item stating its purpose within the system.', verbose_name='Inventory Item Description'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='leveraged_authorizations',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='network_architectures',
            name='description',
            field=ckeditor.fields.RichTextField(help_text="A summary of the system's Network Architecture.", verbose_name='Network Architecture Description'),
        ),
        migrations.AlterField(
            model_name='network_architectures',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='description',
            field=ckeditor.fields.RichTextField(help_text=" A summary of the user's purpose within the system.", verbose_name='User Description'),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='A summary of the system.', null=True, verbose_name='System Description'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='system_implementations',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='system_security_plans',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=ckeditor.fields.RichTextField(help_text=" A summary of the user's purpose within the system.", verbose_name='User Description'),
        ),
        migrations.AlterField(
            model_name='users',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Additional commentary on the containing object.', verbose_name='Remarks'),
        ),
    ]
