# Generated by Django 3.1.6 on 2021-02-04 14:53

from django.db import migrations, models
import django.db.models.deletion
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20210129_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control_parameter',
            options={'ordering': ['short_name', 'control_parameter_id']},
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='connection_security',
            field=models.CharField(choices=[('IPSec', 'Internet Protocal Security (IPSec)'), ('VPN', 'Virtual Private Network (VPN)'), ('SSL', 'Secure Sockets Layer (SSL)'), ('TLS', 'Transport Layer Security (TLS)')], default='TLS', max_length=20),
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='data_direction',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='external_ip_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='external_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.organization'),
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='external_poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.person'),
        ),
        migrations.AddField(
            model_name='system_interconnection',
            name='permitted_protocols',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.protocol'),
        ),
        migrations.AlterField(
            model_name='import_catalog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/'),
        ),
        migrations.AlterField(
            model_name='system_interconnection',
            name='desc',
            field=ssp.models.base_classes_and_fields.customTextField(verbose_name='Information Being Transmitted'),
        ),
    ]
