# Generated by Django 3.1.8 on 2021-10-19 18:24

from django.db import migrations, models
import django.db.models.deletion
import ssp.models.base_classes_and_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20210322_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, help_text='A title for display and navigation', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='A common name, short name, or acronym', max_length=255)),
                ('desc', ssp.models.base_classes_and_fields.customTextField(help_text='A short textual description', verbose_name='description')),
                ('remarks', ssp.models.base_classes_and_fields.customTextField(help_text='general notes or comments')),
                ('type', models.CharField(choices=[('splunk', 'Splunk Search'), ('shell', 'Shell Command')], max_length=255)),
                ('testing_conditions', models.CharField(max_length=2000)),
                ('annotations', ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.annotation')),
                ('links', ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.link')),
                ('properties', ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.element_property')),
                ('results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
