# Generated by Django 3.2.10 on 2022-01-10 16:16

from django.db import migrations
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20220107_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_component',
            name='component_protocols',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.protocol'),
        ),
    ]
