# Generated by Django 3.0.7 on 2020-12-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20201204_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='nist_control',
            name='catalog',
            field=models.CharField(default='TBD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='control_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
