# Generated by Django 3.0.7 on 2020-08-17 16:40

from django.db import migrations, models
import ssp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0002_auto_20200817_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AddField(
            model_name='status',
            name='desc',
            field=ssp.models.customTextField(help_text='A short textual description', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='status',
            name='short_name',
            field=models.CharField(blank=True, help_text='A common name, short name, or acronym', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='title',
            field=models.CharField(blank=True, help_text='A title for display and navigation', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='remarks',
            field=ssp.models.customTextField(help_text='general notes or comments'),
        ),
    ]
