# Generated by Django 3.1 on 2020-08-06 11:31

from django.db import migrations, models
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0003_auto_20200806_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_characteristic',
            name='security_impact_level',
        ),
        migrations.RemoveField(
            model_name='system_information_type',
            name='adjustment_justification',
        ),
        migrations.AddField(
            model_name='system_characteristic',
            name='security_objective_availability',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_characteristic',
            name='security_objective_confidentiality',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_characteristic',
            name='security_objective_integrity',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='system_information_type',
            name='adjusted_availability_impact_justification',
            field=ssp.models.customTextField(),
        ),
        migrations.AddField(
            model_name='system_information_type',
            name='adjusted_confidentiality_impact_justification',
            field=ssp.models.customTextField(),
        ),
        migrations.AddField(
            model_name='system_information_type',
            name='adjusted_integrity_impact_justification',
            field=ssp.models.customTextField(),
        ),
        migrations.AlterField(
            model_name='system_characteristic',
            name='security_sensitivity_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='system_information_type',
            name='adjusted_availability_impact',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='system_information_type',
            name='adjusted_confidentiality_impact',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='system_information_type',
            name='adjusted_integrity_impact',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
    ]
