# Generated by Django 3.0.7 on 2020-08-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0003_auto_20200817_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.hashed_value'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='mediaType',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='rel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
