# Generated by Django 3.1.8 on 2021-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0004_test_evidence_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_evidence',
            name='type',
            field=models.CharField(choices=[('splunk', 'Splunk Search'), ('shell', 'Shell Command'), ('curl', 'Curl Command')], max_length=255),
        ),
    ]
