# Generated by Django 4.1.5 on 2023-01-18 18:27

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0001_squashed_0004_remove_authorization_boundaries_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_characteristics',
            name='security_impact_level',
            field=common.models.ShortTextField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], help_text='The overall level of expected impact resulting from unauthorized disclosure, modification, or loss of access to information.', null=True, verbose_name='Security Impact Level'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='security_objective_availability',
            field=common.models.ShortTextField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], help_text='A target-level of availability for the system, based on the sensitivity of information within the system.', null=True, verbose_name='Security Objective: Availability'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='security_objective_confidentiality',
            field=common.models.ShortTextField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], help_text='A target-level of confidentiality for the system, based on the sensitivity of information within the system.', null=True, verbose_name='Security Objective: Confidentiality'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='security_objective_integrity',
            field=common.models.ShortTextField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], help_text='A target-level of integrity for the system, based on the sensitivity of information within the system.', null=True, verbose_name='Security Objective: Integrity'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='security_sensitivity_level',
            field=common.models.ShortTextField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], help_text='The overall information system sensitivity categorization, such as defined by FIPS-199.', null=True, verbose_name='Security Sensitivity Level'),
        ),
    ]
