# Generated by Django 3.0.7 on 2020-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0003_auto_20201207_1148'),
        ('ssp', '0004_auto_20201207_1334'),
    ]

    operations = [
    ]
