# Generated by Django 3.0.7 on 2020-08-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0004_auto_20200825_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_characteristic',
            name='system_description',
        ),
        migrations.RemoveField(
            model_name='system_characteristic',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='system_characteristic',
            name='system_short_name',
        ),
    ]
