# Generated by Django 3.1 on 2020-08-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0004_auto_20200806_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', ssp.models.customMany2ManyField(blank=True, to='ssp.user_role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssp.person')),
            ],
        ),
        migrations.AddField(
            model_name='system_security_plan',
            name='system_user',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.system_user'),
        ),
    ]
