# Generated by Django 4.1.7 on 2023-02-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_profile', '0005_alter_imports_include_all_and_more'),
        ('ssp', '0005_alter_system_characteristics_security_impact_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_profiles',
            name='local_profile',
            field=models.ForeignKey(help_text="A local profile to use as the system's control baseline.", null=True, on_delete=django.db.models.deletion.CASCADE, to='ctrl_profile.profiles', verbose_name='Profile Reference'),
        ),
    ]
