# Generated by Django 3.1.8 on 2021-10-28 19:10

from django.db import migrations
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0005_auto_20211019_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_evidence',
            name='results',
        ),
        migrations.AddField(
            model_name='test_evidence',
            name='results',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.attachment'),
        ),
    ]
