# Generated by Django 3.0.7 on 2020-08-17 17:13

from django.db import migrations, models
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0005_auto_20200817_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_control_statement',
            name='control_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nist_control_statement',
            name='statement_type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='sspBasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotations', ssp.models.customMany2ManyField(blank=True, to='ssp.annotation')),
                ('links', ssp.models.customMany2ManyField(blank=True, to='ssp.link')),
                ('properties', ssp.models.customMany2ManyField(blank=True, to='ssp.element_property')),
            ],
        ),
    ]
