# Generated by Django 3.1 on 2020-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0005_auto_20200806_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_security_plan',
            old_name='system_user',
            new_name='system_users',
        ),
    ]
