# Generated by Django 4.1.7 on 2023-02-23 20:00

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0006_import_profiles_local_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_profiles',
            name='href',
            field=common.models.ShortTextField(blank=True, help_text="A resolvable URL reference to the profiles to use as the system's control baseline.", verbose_name='Profile Reference'),
        ),
    ]
