# Generated by Django 3.0.7 on 2020-08-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0006_auto_20200817_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sspBasicModel',
        ),
    ]
