# Generated by Django 3.1 on 2020-08-10 19:06

from django.db import migrations, models
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0006_auto_20200806_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_control_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('controls', ssp.models.customMany2ManyField(blank=True, to='ssp.system_control')),
            ],
        ),
    ]
