# Generated by Django 3.0.7 on 2020-08-26 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0007_delete_leveraged_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_implementation',
            name='nist_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ssp.nist_control'),
        ),
        migrations.AlterField(
            model_name='system_control',
            name='control_origination',
            field=models.CharField(choices=[('Service Provider Corporate ', 'Service Provider Corporate'), ('Service Provider System Specific ', 'Service Provider System Specific'), ('Service Provider Hybrid (Corporate and System Specific)', 'Service Provider Hybrid'), ('Configured by Customer (Customer System Specific) ', 'Configured by Customer'), ('Provided by Customer (Customer System Specific) ', 'Provided by Customer'), ('Shared (Service Provider and Customer Responsibility) ', 'Shared'), ('Inherited ', 'Inherited'), ('N/A', 'N/A')], max_length=100),
        ),
        migrations.AlterField(
            model_name='system_control',
            name='control_status',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Partially Implemented ', 'Partially Implemented'), ('Planned ', 'Planned'), ('Alternative Implementation', 'Alternative Implementation'), ('Not Applicable', 'Not Applicable'), ('Other than Implemented', 'Other than Implemented')], max_length=100),
        ),
    ]
