# Generated by Django 3.1 on 2020-08-10 23:04

from django.db import migrations
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0007_system_control_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_security_plan',
            name='control_groups',
            field=ssp.models.customMany2ManyField(blank=True, to='ssp.system_control_group'),
        ),
    ]
