# Generated by Django 3.0.7 on 2020-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0007_delete_sspbasicmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nist_control',
            name='control_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='group_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='sort_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
