# Generated by Django 3.1.8 on 2021-11-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0007_auto_20211105_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_evidence',
            old_name='result',
            new_name='results',
        ),
    ]
