# Generated by Django 3.0.7 on 2020-08-26 11:53

from django.db import migrations, models
import django.db.models.deletion
import ssp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0008_auto_20200825_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='nist_control_statement',
            name='nist_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ssp.nist_control'),
        ),
        migrations.AlterField(
            model_name='nist_control',
            name='control_statements',
            field=ssp.models.customMany2ManyField(blank=True, related_name='stmt', to='ssp.nist_control_statement'),
        ),
    ]
