# Generated by Django 3.1.8 on 2021-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0008_auto_20211105_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_evidence',
            name='results',
            field=models.FileField(upload_to=''),
        ),
    ]
