# Generated by Django 3.0.7 on 2020-08-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0009_auto_20200826_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nist_control',
            name='control_statements',
        ),
        migrations.RemoveField(
            model_name='nist_control_statement',
            name='control_id',
        ),
    ]
