# Generated by Django 3.1.8 on 2021-11-08 18:38

from django.db import migrations
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0009_auto_20211105_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_evidence',
            name='results',
        ),
        migrations.AddField(
            model_name='test_evidence',
            name='results',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.attachment'),
        ),
    ]
