# Generated by Django 4.2.5 on 2023-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_citations_links_alter_metadata_links_and_more'),
        ('ssp', '0009_alter_authorization_boundaries_diagrams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization_boundaries',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='data_flows',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='diagrams',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='information_type_impact_level',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='information_types',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='leveraged_authorizations',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='network_architectures',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='system_characteristics',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='system_implementations',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='systems_information',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='users',
            name='links',
            field=models.ManyToManyField(blank=True, to='common.links', verbose_name='Links'),
        ),
    ]
