# Generated by Django 3.0.7 on 2020-10-01 22:15

from django.db import migrations, models
import ssp.models.base_classes_and_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0015_auto_20200930_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control_statement',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='information_type',
            name='availabilityImpact',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='information_type',
            name='confidentialityImpact',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='information_type',
            name='integrityImpact',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='system_component',
            name='component_information_types',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.information_type'),
        ),
        migrations.AlterField(
            model_name='system_security_plan',
            name='system_information',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.information_type'),
        ),
        migrations.AlterField(
            model_name='system_service',
            name='service_information_types',
            field=ssp.models.base_classes_and_fields.customMany2ManyField(blank=True, to='ssp.information_type'),
        ),
        migrations.DeleteModel(
            name='system_information_type',
        ),
    ]
