# Generated by Django 3.0.7 on 2020-10-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssp', '0016_auto_20201001_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_security_plan',
            old_name='system_information',
            new_name='information_types',
        ),
    ]
