name: Docker Image CI

on:
  push:
    branches: [ opal_v2 ]
  pull_request:
    branches: [ opal_v2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opal:$(date +%s)
